---
title: "Lab 2 - Linguistics Data, Stat 215A, Fall 2020"
author: "Your name"
date: "`r format(Sys.time(), '%B %d, %Y')`"
header-includes:
   - \usepackage{float}
output: 
  pdf_document:
    number_sections: true
---


```{r setup, echo = FALSE, message=FALSE, warning=FALSE}
# load in useful packages
remove(list = ls())

library(Rtsne)
library(maps)
library(ggplot2)
library(dplyr)
library(knitr)
library(here)
library(kernlab)
library(keras)
library(pander)
library(grid)
library(gridExtra)

# set default knitr chunks
knitr::opts_chunk$set(
  echo = FALSE,  # don't print the code chunk
  warning = FALSE,  # don't print warnings
  message = FALSE,  # don't print messages
  fig.width = 6,  # set default width of figures
  fig.height = 4,  # set default height of figures
  fig.align = "center",  # always align figure in center
  fig.pos = "H",  # always plot figure at the exact location of the code chunk
  cache = FALSE)  # don't cache results

# load in the loadData() functions
source(here("R/utils.R"))
source(here("R/clean.R"))

ling_data <- read.table(here('data/lingData.txt'), header = T)
ling_location <- read.table(here('data/lingLocation.txt'), header = T)
ling_clean <- cleanLingData(ling_data)
# question_data contains three objects: quest.mat, quest.use, all.ans
load(here("data/question_data.RData"))
state_df <- map_data("state")

ling_1h_file <- here('data/ling_1h.csv')
if (!file.exists(ling_1h_file)){
ling_1h <- oneHotEncoder(ling_clean, FALSE)
write.csv(ling_1h, ling_1h_file,  row.names = FALSE)
}
ling_1h <- read.csv(ling_1h_file)

```


```{r,echo=FALSE, out.width='.75\\linewidth', fig.width=15, fig.height=12,fig.show='hold',fig.align='center', fig.cap='Log Odds ratio for question 51 between the observed response in each state and the expected values under the assumption that all states are identical it terms of answers distribution'}
plotLogOdds(120)
plotLogOdds(109)
plotLogOdds(50, TRUE)


```
